// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoo1EVkvjpzKbbZJSNfa0kV4dId1hD2z0',
    appId: '1:1017185762494:android:fac64d972ec9acc62ff2ef',
    messagingSenderId: '1017185762494',
    projectId: 'smartirrigation-8d59c',
    databaseURL: 'https://smartirrigation-8d59c-default-rtdb.firebaseio.com',
    storageBucket: 'smartirrigation-8d59c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ps7MmqJmwfk0FTZEROUeP5cVlTakXyM',
    appId: '1:1017185762494:ios:a524b9df5ffb40a52ff2ef',
    messagingSenderId: '1017185762494',
    projectId: 'smartirrigation-8d59c',
    databaseURL: 'https://smartirrigation-8d59c-default-rtdb.firebaseio.com',
    storageBucket: 'smartirrigation-8d59c.appspot.com',
    iosBundleId: 'com.example.smartIrriApp',
  );
}
